// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7nw07S3RFMzd9I2lraD4GOkFJIP9QzE',
    appId: '1:686135322852:web:b8f51d4efc5eb27ac264f1',
    messagingSenderId: '686135322852',
    projectId: 'studio-4987857081-7c656',
    authDomain: 'studio-4987857081-7c656.firebaseapp.com',
    storageBucket: 'studio-4987857081-7c656.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpp2FVK7ZCwRbr6VddDMo-_EyP0BZnCs0',
    appId: '1:290517835892:android:be61e3888a5130cefb3121',
    messagingSenderId: '290517835892',
    projectId: 'pawconnect-490903',
    storageBucket: 'pawconnect-490903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKlZcIPo1Qi5iNLAyRh3rC7_5VYPRnxQ',
    appId: '1:686135322852:ios:45777080cba0a1a0c264f1',
    messagingSenderId: '686135322852',
    projectId: 'studio-4987857081-7c656',
    storageBucket: 'studio-4987857081-7c656.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
